# syntax=docker/dockerfile:1

FROM ubuntu:latest 

RUN apt update
RUN apt upgrade -y
RUN apt install curl -y
RUN apt install net-tools -y
RUN apt install dnsutils -y
RUN apt install iputils-ping -y
RUN apt install ssh -y
RUN apt install telnet -y